---
- name: Testing andrewrothstein.opa
  hosts: all
  tasks:
    - name: Installing andrewrothstein.opa
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Executing 'opa version'
      ansible.builtin.command: opa version
      changed_when: false
      register: opa_test_output
    - name: Output of 'opa version'
      ansible.builtin.debug:
        msg: '{{ opa_test_output.stdout }}'
