---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ opa_url }} to {{ opa_fq_ver_exe }}
  become: yes
  become_user: root
  get_url:
    url: '{{ opa_url }}'
    dest: '{{ opa_fq_ver_exe }}'
    checksum: '{{ opa_checksum }}'
    mode: 0755
- name: linking {{ opa_fq_link_exe }} to {{ opa_fq_ver_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ opa_fq_ver_exe }}'
    dest: '{{ opa_fq_link_exe }}'
    state: link
